name: SIGApp
description: The unofficial SIGA app.

version: 1.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  
  flutter_bloc: ^3.0.0
  equatable: ^1.0.1
  # shared_preferences: ^0.5.6
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  url_launcher: ^5.4.1
  diagonal_scrollview: ^0.0.4+1
  flutter_circular_chart: ^0.1.0
  screenshot: ^0.1.1
  esys_flutter_share: ^1.0.2
  # flutter_webview_plugin: ^0.3.10
  flutter_webview_plugin: ^0.3.10+2
  html: ^0.14.0+3
  charts_flutter: ^0.8.1
  fl_chart: ^0.8.0
  firebase_core: ^0.4.4+2  
  # cloud_firestore: ^0.13.4+1
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.3
  bot_toast: ^2.4.0
  animate_do: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets\fonts\ProductSans\ProductSans-Regular.ttf
        - asset: assets\fonts\ProductSans\ProductSans-Italic.ttf
          style: italic
        - asset: assets\fonts\ProductSans\ProductSans-Bold.ttf
          weight: 700
    - family: Sigapp
      fonts:
        - asset: assets\fonts\Sigapp\montserrat-regular.ttf
  assets:
    # - assets/images/custom_epii_logo.png
    - assets/images/
    - assets/nota_del_autor.txt
  
  uses-material-design: true